# Groq API Key Configuration
# =========================
# To get your API key:
# 1. Visit https://console.groq.com/
# 2. Sign in to your account
# 3. Click on "API Keys" in the sidebar
# 4. Click "Create API Key" or copy an existing key
# 5. Replace the placeholder below with your actual key
#    - The key should start with "gsk_"
#    - Do not include any quotes or spaces
#    - Example: GROQ_API_KEY = gsk_1234567890abcdef
GROQ_API_KEY = "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"

# Email Configuration
# ==================
# Replace these with your actual Gmail credentials
# Make sure to use the App Password, not your regular Gmail password
EMAIL_ADDRESS = "saijashwanth173@gmail.com"  # Replace with your Gmail address
EMAIL_PASSWORD = "assdhswgcvdjiqtg"  # Replace with your App Password

# Firebase Configuration
FIREBASE_API_KEY = "AIzaSyDrQ9latJqDfA1y3HfL0QBxQj0-tHCF8zA"  # Your actual API key
FIREBASE_AUTH_DOMAIN = "mindspace-e0d7a.firebaseapp.com"
FIREBASE_PROJECT_ID = "mindspace-e0d7a"
FIREBASE_STORAGE_BUCKET = "mindspace-e0d7a.appspot.com"
FIREBASE_MESSAGING_SENDER_ID = "1234567890"  # Get this from Firebase Console
FIREBASE_APP_ID = "1:1234567890:web:abcdef123456"  # Get this from Firebase Console 